<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INLEN852002488B" failures="1" tests="2" name="Test" time="5.742" errors="0" timestamp="2022-11-13T01:28:24 IST">
  <testcase classname="com.snowflake.setup.SnowflakeTestng" name="CsvCompare" time="0.378">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at com.snowflake.setup.SnowflakeTestng.areCsvDataSameAsDb(SnowflakeTestng.java:283)
at com.snowflake.setup.SnowflakeTestng.CsvCompare(SnowflakeTestng.java:126)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- CsvCompare -->
  <testcase classname="com.snowflake.setup.SnowflakeTestng" name="connection" time="0.463"/>
</testsuite> <!-- Test -->
